core/urls.py
from django.urls import path
from .views import *

urlpatterns = [

]

usuario/urls.py
from django.urls import path

from .views import *

urlpatterns = [
     path('usuarios/', usuarios.as_view(), name='usuarios'),
     path('registro/', registro, name='registro'),
     path('mod_usuario/<pk>/', UserUpdateView.as_view(), name='mod_usuario'),
     path('cambiar_contrasena/', Cambiar_contrasena.as_view(), name='cambiar_contrasena'), 
     path('permisos_usuario/', Permisos_usuario.as_view(), name='accesos'),
     path('todos_permisos/<id>/', todos_permisos, name='todos_permisos'),
]

pedido/models.py
import uuid
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models
from django.utils import timezone

from producto.models import Producto
from usuario.models import Usuario
from producto.models import TIPO_PRODUCTO

ACTIVO_CAJA = (
    (0, 'Cancelado'),
    (1, 'Por pagar'),
    (2, 'Pagado'),
)
ACTIVA_COMANDA = (
    (0, 'Cancelado'),
    (1, 'Activa'),
    (2, 'Pre-pagada'),
    (3, 'Cerrada'),
    (4, 'Cerrada sin pagar'),
)
ACTIVO_DETALLE = (
    (0, 'Cancelado'),
    (1, 'Solicitado'),
    (2, 'Elaborado'),
    (3, 'Entregado'),
    (4, 'Cancelado elaborado'),
    (5, 'Cancelado difinitivo'),
)
ACTIVO_PAGO = (
    (0, 'Cancelado'),
    (1, 'Pagado'),
)
ACTIVO_PROMOCION = (
    (0, 'No presentar'),
    (1, 'Presentar'),
)
ESTADO_DIA = (
    (0, 'Cancelado'),
    (1, 'Activo'),
    (2, 'Cerrado'),
)

class DiaContable(models.Model):
    estatus = models.IntegerField("Estatus", choices=ESTADO_DIA, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)
    token = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    class Meta:
        verbose_name = 'Día contable'
        verbose_name_plural = 'Días contable'
        ordering = ['-fecha_alta',]
        db_table = 'DiaContable'

class Comanda(models.Model):
    mesa = models.CharField("Mesa", max_length=255, null=True, blank=True)
    observacion = models.CharField("Observación", max_length=255, null=True, blank=True)
    dia_contable = models.ForeignKey(DiaContable, on_delete=models.CASCADE, related_name="DiaContable")
    estatus = models.IntegerField("Estatus", choices=ACTIVA_COMANDA, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Comanda'
        verbose_name_plural = 'Comandas'
        ordering = ['-dia_contable', '-fecha_alta',]
        unique_together = ('mesa', 'observacion', 'dia_contable')
        db_table = 'Comanda'

    def __str__(self):
        return ' %s / %s' % (self.mesa, self.observacion)

class Servicio(models.Model):
    comanda = models.ForeignKey(Comanda, on_delete=models.CASCADE, related_name="ComandaServicio")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioServicio", null=True, blank=True)
    actividad = models.CharField("Actividad", max_length=255)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        ordering = ['comanda', '-fecha_alta',]
        db_table = 'Servicio'

    def __str__(self):
        return ' %s, %s, %s' % (self.comanda, self.usuario)

class Caja(models.Model, PermissionRequiredMixin):
    comanda = models.ForeignKey(Comanda, on_delete=models.CASCADE, verbose_name="Comanda")
    caja_grupo = models.ForeignKey('Pago', on_delete=models.CASCADE, verbose_name="Pago_grupo", null=True, blank=True)
    descripcion = models.CharField("Tipo", max_length=255) # Producto, Paquete o Insumo
    especifico = models.CharField("Descripción", max_length=255, null=True, blank=True) # Nombre del anterior campo
    cantidad = models.IntegerField("Cantidad", default=1)
    precio_unitario = models.DecimalField("Precio unitario", max_digits=10, decimal_places=2, default=0)
    importe = models.DecimalField("Importe", max_digits=10, decimal_places=2, default=0)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_CAJA, default=1)
    descripcion_cancela = models.CharField("Cancelación por", max_length=255, null=True, blank=True)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Operación'
        verbose_name_plural = 'Operaciones'
        ordering = ['comanda','-fecha_alta',]
        db_table = 'Caja'

    def __str__(self):
        return ' %s, %s, %s, %s' % (self.comanda, self.descripcion, self.importe, dict(ACTIVO_CAJA).get(self.estatus))

class Pago(models.Model, PermissionRequiredMixin):
    importe_efectivo = models.DecimalField("Efectivo", max_digits=10, decimal_places=2, default=0)
    importe_tarjeta = models.DecimalField("Tarjeta", max_digits=10, decimal_places=2, default=0)
    importe_transferencia = models.DecimalField("Transferencia", max_digits=10, decimal_places=2, default=0)
    importe_descuento = models.DecimalField("Descuento", max_digits=10, decimal_places=2, default=0)
    importe_comision = models.DecimalField("Comisión", max_digits=10, decimal_places=2, default=0)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="UsuarioPago", null=True, blank=True)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_PAGO, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'
        ordering = ['-fecha_alta',]
        db_table = 'Pago'

    def __str__(self):
        return ' %s, %s' % (self.fecha_modificacion, dict(ACTIVO_PAGO).get(self.estatus))

class Detalle(models.Model, PermissionRequiredMixin):
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE, verbose_name="Caja")
    comanda = models.ForeignKey(Comanda, on_delete=models.CASCADE, verbose_name="ComandaDetalle")
    tipo = models.IntegerField("Tipo", choices=TIPO_PRODUCTO, default=1)
    producto = models.CharField("Producto", max_length=255, null=True, blank=True)
    especificacion = models.CharField("Detalle", max_length=255, null=True, blank=True)
    nota = models.CharField("Observación", max_length=255)
    cantidad = models.IntegerField("Cantidad", default=1)
    estatus = models.IntegerField("Estatus", choices=ACTIVO_DETALLE, default=1)
    fecha_modificacion = models.DateTimeField("Fecha modificación", auto_now=True)
    fecha_alta = models.DateTimeField("Fecha alta", auto_now_add=True)

    class Meta:
        verbose_name = 'Detalle'
        verbose_name_plural = 'Detalles'
        ordering = ['-fecha_alta',]
        db_table = 'Detalle'

    def __str__(self):
        return ' %s, %s, %s, %s' % (self.comanda, self.fecha_alta, dict(ACTIVO_DETALLE).get(self.estatus))

usuario/models.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

ES_CLIENTE = (
    (False, 'No'),
    (True, 'Si'),
)

class Usuario(AbstractUser):
    celular = models.CharField(max_length=20, blank=True, null=True)
    cliente = models.BooleanField('Cliente', choices=ES_CLIENTE, default=False)
    
    class Meta:
        db_table = 'Usuario'
        permissions = (
            ('cocina', 'Consulta cocina'),
            ('bar', 'Consulta bar'),
            ('servicio', 'Solicitudes comanda'),
            ('entregas', 'Consulta entregas'),
            ('consultas_seguimiento', 'Consulta de seguimiento'),
            ('consulta_comandas', 'Consulta comandas'),
            ('consulta_servicios', 'Consulta de servicios'),
            ('catalogo', 'Consulta catálogo'),
            ('accesos', 'Consulta accesos'),
            ('abrir', 'Día abre'),
            ('cerrar', 'Día cierra'), 
            ('usuarios', 'Consulta usuarios'),
            ('caja', 'Pago de comandas'),
            ('global', 'Reporte global diario'),
            ('complace', 'Poner canciones a clientes'),
            ('presenta', 'Muestra QR para música'),
            ('musica', 'Lista de complacencias'),
        )

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import PasswordInput

from .models import Usuario

class UsuarioForm(UserCreationForm):
    cliente = forms.BooleanField(widget=forms.CheckboxInput)

    class Meta:
        model = Usuario
        fields = ['username', 'cliente', 'first_name', 'last_name', 'celular', 'email', 'password1', 'password2']
        labels = {
            'username': 'Usuario',
            'Cliente': 'Cliente',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'celular': 'Celular',
            'email': 'Correo',
            'password1': 'Contraseña',
            'password2': 'Confirmación'
            }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['cliente'].required = False
        self.fields['celular'].required = True
        self.fields['email'].required = True
        self.fields['password1'].required = False
        self.fields['password2'].required = False

class UsuarioFormEdit(forms.ModelForm):
    cliente = forms.BooleanField(widget=forms.CheckboxInput, label='')
    is_active = forms.BooleanField(widget=forms.CheckboxInput, label='')
    password = forms.CharField(
        widget=PasswordInput(attrs={'autocomplete': 'new-password'}),
        required=False,
        label='Nueva Contraseña'
    )

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'cliente', 'celular', 'email', 'is_active', 'password']
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'cliente': 'Cliente',
            'celular': 'Celular',
            'email': 'Correo',
            'is_active': 'Activo',
            }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['cliente'].required = False
        self.fields['celular'].required = True
        self.fields['email'].required = True
        self.fields['is_active'].required = False
        
        for form in self.visible_fields():
            if not (form.name == 'cliente' or form.name == 'is_active'):
                form.field.widget.attrs['class'] = 'form-control'


class CambiaContrasenaForm(forms.Form):
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs = {
                'class': 'form-control',
                'placeholder': 'Ingrese su nueva contraseña...',
                'id':'password1',
                'required': 'required',
            }
        )
    )   
    password2 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs = {
                'class': 'form-control',
                'placeholder': 'Confirme nueva contraseña...',
                'id':'password2',
                'required': 'required',
            }
        )
    )
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('Contraseñas no coinciden !')
        return password2

usuario/templates/usuario/cambiar_contrasena.html
{% extends "core/base.html" %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-8 col-sm-6 col-md-5 col-lg-5 col-xl-4 col-xxl-3">
        <div class="card">
            <div class="card-body">
                <h2>Cambiar contraseña</h2>
                <hr>
                <form action="" method="post" onkeypress="return anular(event)">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-10 mb-0">
                            {{ form.password1 }}
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="form-group col-10 mb-0">
                            {{ form.password2 }}
                        </div>
                    </div>
                    <br>
                    <div>
                        <input type="submit" value="Guardar" class="btn btn-success">
                        <a href="{% url 'index' %}" class="btn btn-danger">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

usuario/templates/usuario/permisos_usuario.html
{% extends "core/base.html" %}
{% load static %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block content %}
{% if user.is_authenticated and accesos_perm %}
<div class="container mt-4">
  <div class="text-center">
    <h2>Accesos</h2>
  </div>
</div>
<div class="container col-11 col-xs-7 col-sm-7 col-md-7 col-lg-6 col-xl-5 col-xxl-4">
  <form method="post" action="{% url 'accesos' %}">
    {% csrf_token %}
    <div class="row d-flex justify-content-start">
      <a href="{% url 'index'  %}" class="btn btn-secondary col-2">Regresar</a>
      {% if accesos_modificar_perm %}
      <button type="submit" id="boton_guarda" class="btn btn-success col-2 ms-3">Guardar</button>
      {% endif %}
    </div>
    <div class="mt-3">
      <select class="form-select" name="usuario" id="id_usuario">
        <option value="0">Seleccione usuario</option>
        {% for user in users %}
        <option value="{{ user.id }}">{{ user.username }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-12 col-xs-7 col-sm-7 col-md-7 col-lg-6 col-xl-5 col-xxl-4 mt-3"></div>
    <table class="table cuadro table-striped col-12">
      <tbody id="todos_permisos">
      </tbody>
    </table>
  </form>
</div>
<script>
  $("#boton_guarda").hide()
  $('#id_usuario').change(function () {
    var id = $(this).val();
    if (id == 0) {
      $("#todos_permisos").empty();
      $("#boton_guarda").hide()
    } else {
      $("#boton_guarda").show()
      $.ajax({
        url: '/usuario/todos_permisos/' + id + '/',
        type: 'GET',
        dataType: 'json',
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        success: function (data) {
          // Obtener los permisos del usuario del objeto de datos recibido
          var userPermissions = data.usuario_permisos;

          // Generar la tabla de permisos dinámicamente
          var tableBody = $('#todos_permisos');
          tableBody.empty();

          // Iterar sobre los permisos y generar las filas de la tabla
          var row = $('<tr class="col-12"></tr>');
          $.each(data.permisos, function (index, permission) {
            var cell = $('<td class="col-4"></td>');
            {% if accesos_modificar_perm %}
            var checkbox = $('<input type="checkbox" name="permissions" id="permission_' + permission.id + '" value="' + permission.id + '">');
            {% else %}
            var checkbox = $('<input type="checkbox" disabled name="permissions" style="opacity: 0.9; background-color: black;" id="permission_' + permission.id + '" value="' + permission.id + '">');
      {% endif %}
      var label = $('<label style="margin-left: 5px;" for="permission_' + permission.id + '">' + permission.name + '</label>');

      // Verificar si el permiso está asignado al usuario y marcar el checkbox en consecuencia
      if (userPermissions.includes(permission.id)) {
        checkbox.prop('checked', true);
      }

      cell.append(checkbox);
      cell.append(label);
      row.append(cell);

      // Agregar una nueva fila cada 4 permisos
      if ((index + 1) % 2 === 0 || (index + 1) === data.permisos.length) {
        tableBody.append(row);
        row = $('<tr class="col-12"></tr>');
      }
    });
        },
  error: function (xhr, textStatus, errorThrown) {
    console.log('Error:', errorThrown);
  }
      });
    }
  });
</script>
{% endif %}
{% endblock %}

usuario/templates/usuario/registro.html
{% extends "core/base.html" %}
{% load static %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block content %}
<div class="container mt-4">
  <h2 class="text-center">Registro Usuario</h2>
  <form method="post">
    {% csrf_token %}
    <div class="d-flex justify-content-start mb-3">
      <a href="{% url 'usuarios' %}" class="btn btn-secondary cuadro-boton">Regresar</a>
      <button class="btn btn-success ms-3" type="submit">Guardar</button>
    </div>
    <table id="tabla">
      {{form.as_table}}
    </table>
  </form>
</div>
<script>
  $(document).ready(function () {
    var $tdElements1 = $('table tr');
    $tdElements1.addClass('align-text-top');
    $('label[for="id_password2"]').text('Confirmación:');
  });
</script>
{% endblock %}

usuario/templates/usuario/usuario.html
{% extends "core/base.html" %}
{% load static %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
{% if modifica_usuario_perm %}
<div class="container mt-4">
    <h2 class="text-center">Usuario <strong>{{ usuario }}</strong></h2>
    <form method="POST" class="row g-3">
        {% csrf_token %}
        <div class="d-flex justify-content-start mb-3">
            <a href="{% url 'usuarios' %}" class="btn btn-secondary">Regresar</a>
            <button type="submit" class="btn btn-success ms-3">Guarda</button>
        </div>
        <div class="row d-flex justify-content-around text-center">
            <h4 style="color: rgb(11, 125, 231);">{{accion}}</h4>
        </div>
        <div class="col-12">
            {{ form.first_name.label }}
            {{ form.first_name }}
        </div>
        <div class="col-12">
            {{ form.last_name.label }}
            {{ form.last_name }}
        </div>
        <div class="col-6">
            {{ form.celular.label }}
            {{ form.celular }}
        </div>
        <div class="col-1 text-center">
            Activo
            <div class="col-12" style="margin-left: 7px; margin-top: 5px;">
                {{ form.is_active }}
            </div>
        </div>
        <div class="col-1 text-center" >
            Cliente
            <div class="col-12" style="margin-left: 7px; margin-top: 5px;">
                {{ form.cliente }}
            </div>
        </div>
        <div class="col-12">
            {{ form.email.label }}
            {{ form.email }}
        </div>
        <div class="col-12">
            {{form.password.label }}
            {{form.password }}
        </div>
        <div class="row d-flex justify-content-around">
        </div>
    </form>
</div>
<script>
    $("#id_cliente").addClass('checkbox-large');
    $("#id_is_active").addClass('checkbox-large');
</script>
{% endif %}
{% endif %}
{% endblock %}

usuario/templates/usuario/usuario_confirm_delete.html
<h2>¿Estás seguro que deseas eliminar al usuario {{ object.username }}?</h2>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
    <a href="{% url 'usuarios' %}">Cancelar</a>
</form>

usuario/templates/usuario/usuarios.html
{% extends "core/base.html" %}
{% load static %}
{% block blcss %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% endblock %}
{% block content %}
{% if user.is_authenticated and usuarios_perm %}
<div class="container mt-4">
    <h2 class="text-center">Usuarios</h2>
    <div class="d-flex justify-content-between mb-3">
        <a href="{% url 'registro' %}" class="btn btn-success">Nuevo usuario</a>
    </div>
    <table class="table table-striped table-bordered mt-3">
        <thead class="table-dark">
            <tr class="text-center">
                <th class="col-4">Nombre</th>
                <th class="col-2">Usuario</th>
                <th class="col-3">Correo</th>
                <th class="col-2">Celular</th>
                <th class="col-1">Cliente</th>
            </tr>
        </thead>
        <tbody>
            {% for user in usuarios %}
            <tr>
                <td class="align-middle">
                    {% if modifica_usuario_perm %}
                    <a href="{% url 'mod_usuario' user.id %}" style="text-decoration: none; font-weight: bold; font-style: italic;">
                    {{ user.first_name }} {{ user.last_name }}
                    </a>
                    {% else %}
                    <a href="#" style="text-decoration: none; ">
                        {{ user.first_name }} {{ user.last_name }}
                    </a>    
                    {% endif %}
                </td>
                <td class="text-center align-middle">{{ user.username }}</td>
                <td class="text-center align-middle">{{ user.email|default_if_none:"" }}</td>
                <td class="text-center align-middle">{{ user.celular|default_if_none:"" }}</td>
                <td class="text-center align-middle">{{ user.get_cliente_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}